# Generated by Django 6.0.3 on 2026-03-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('capacity', models.PositiveIntegerField(verbose_name='Вместимость (чел.)')),
                ('price_per_hour', models.PositiveIntegerField(verbose_name='Цена за час (₽)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('has_projector', models.BooleanField(default=False, verbose_name='Есть проектор')),
                ('has_board', models.BooleanField(default=False, verbose_name='Есть доска')),
                ('has_wifi', models.BooleanField(default=True, verbose_name='Есть Wi-Fi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='spaces/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Помещение',
                'verbose_name_plural': 'Помещения',
            },
        ),
    ]
